### ISSUE TITLE
No lib download?

### ISSUE THREAD

**Issue by Sir-Will** [nallar/ModPatcher#15]
hey,
is there a reason that there is no longer a lib download which includes the dependencies?

**Comment by LunNova** [comment]
Dependencies are now intended to be bundled/downloaded using [LibLoader](https://github.com/MinimallyCorrect/LibLoader).

See TickProfiler's build.gradle for how this is set up: https://github.com/MinimallyCorrect/TickProfiler/blob/1.12/build.gradle

ModPatcher should have a separate download which allows it to be used on its own instead of as a library, but I forgot to do that. #16.

**Comment by Sir-Will** [comment]
I'm using both but somehow the latest build doesn't create the ModPatcher dir and log file so I thought the dependencies were misisng.

**Comment by Sir-Will** [comment]
Any news to this issue? I would really like to use the latest TickProfiler and ModPatcher version.

**Comment by LunNova** [comment]
Put tickprofiler in your mods folder. Problem solved?

There is no separate lib download but that won't stop you using it.

**Comment by Sir-Will** [comment]
I did that, the issue is that it doesn't create the ModPatches directory and doesn't load any patches while there are no errors in the log.

**Comment by LunNova** [comment]
It should still load patches from /ModPatches. Upload your fml log please?

**Comment by Sir-Will** [comment]
https://gist.github.com/Sir-Will/4db84e8e4d3f8850f818396b6612af1a

**Comment by LunNova** [comment]
Can you remove the ModPatcher jar from your mods folder, then update TickProfiler to build 59?

It looks like three patches were loaded, but due to a bug the debug output is not as good as it should be.

https://gist.github.com/Sir-Will/4db84e8e4d3f8850f818396b6612af1a#file-gistfile1-txt-L120

There aren't any later errors, but only two classes get patched. Possibly the class you're patching either doesn't match the name of any class which actually gets loaded, or that class is in the classloader transformer exclusion list and can't be patched.

The new build fixes the debug logging there so if you run with it and post the log it should include some more information.

**Comment by Sir-Will** [comment]
Hm, so ModPatcher is in TickProfiler included now?
I didn't add any patches yet, the 3 patches are the ones from TickProfiler I think.

I just added a patch and now it shows 4. Will test in a moment if the patch worked.

**Comment by Sir-Will** [comment]
Seems to work.

What confused me is that it no longer creates the ModPatches directory and the ModPatcher.log and I couldn't check for errors patch errors because of that, that's why I thought it was broken.

Any chance to get the `ModPatcher.log` file back? Makes it much easier to find and read the errors.

**Comment by LunNova** [comment]
Good to hear that it's still working :)

There will eventually be a separate standalone ModPatcher download again with the same logging behaviour and automatic creation of the ModPatches folder.

Tracking that issue under #16.
